### ISSUE TITLE
about macro `seq` & one typo in readme

### ISSUE THREAD

**Issue by tu10ng** [PuellaeMagicae/unix-in-lisp#12]
不确定如何提 issue, 如果提供的信息不清楚请指出

unix-in-lisp 和 ultralisp 都是最新版本

根据 TUTORIAL.org 尝试 mcd 函数时, 第一次运行 mcd, 提示 -p flag 变成了大写的 -P flag; 第二次运行, 提示无法进入目录, 且目录没有创建. 好像重启 unix-in-slime 后也可以复现.
![20230527_020506](https://github.com/PuellaeMagicae/unix-in-lisp/assets/47939948/eb668c18-f14a-4408-9f8c-4b719707b985)

 但是如果不用 mcd, 只用 mkdir -p , 则不会提示 flag 变成大写, 并且可以成功创建目录.
![20230527_022202](https://github.com/PuellaeMagicae/unix-in-lisp/assets/47939948/96d5a2c2-e429-4cbe-8e27-20f9282ab1f7)

把 seq 换成 progn 就可以运行 (表示不懂 seq 的原理)
![20230527_021057](https://github.com/PuellaeMagicae/unix-in-lisp/assets/47939948/84082765-54ef-4644-8781-bee3bad0917e)

typo:
README.org第 35 行, 应该是 (pipe (ls) (wc -l))

**Comment by kchanqvq** [comment]
感谢指出！哇，咱之前没考虑到这个问题，看来 `seq/&&/||` 目前的实现方法完全是错的，得用不同的方法了。

目前 `seq/&&/||` 会开一个 `lisp-process`，类似 subshell，因为 Unix in Lisp 里的有效进程都是异步的而且不能直接继承 stdin/stdout（实际上有问题的是 stdin，因为 SLIME 需要显式调用 `read-char` 之类的过程才会读取用户输入），所以直接顺序等待的实现方法不能用。于是我之前就用现成的 `lisp-process` 开了个新线程，在新线程里顺序等待并处理输入输出。但这样问题是新线程有自己的一套动态环境（比如当前目录），这样在 `seq` 里的更改就不会传播到原本的 REPL 了。`-P` 问题是因为在目前新线程里没设置 `*readtable*`，不过光修这个的意义不大，我感觉这整个实现思路就行不通。

正确的方法应该是不开新线程，然后在每个命令的 `status-change-hook` 里运行下一个命令，我看看这几天能不能写出来。

`progn` 没有 `seq` 的问题，但对于更复杂的例子大概不是直观想要的效果。因为命令都是异步的，所以 `(progn cmd1 cmd2 cmd3)` 会并发执行 `cmd1 cmd2 cmd3`。正确实现的 `(seq cmd1 cmd2 cmd3)` 应该会顺序执行，但咱得先修修。

**Comment by kchanqvq** [comment]
79da9ab workaround 了一下，`TUTORIAL.org` 里改用 `fg` 了。看了看万恶之源 POSIX shell 也会在不少地方开 subshell，所以实现以上“正确的方法”打算先放放，具体实现起来有些问题咱也还没想清楚。
